/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, Signer} from "ethers";
import {Provider} from "ethers/providers";

import {IbFactory} from "./IbFactory";

export class IbFactoryFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IbFactory {
    return new Contract(address, _abi, signerOrProvider) as IbFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "newBPool",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address"
      }
    ],
    stateMutability: "nonpayable",
    type: "function"
  }
];
