/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ISmartPoolRegistryInterface extends Interface {
  functions: {
    addSmartPool: TypedFunctionDescription<{
      encode([_smartPool]: [string]): string;
    }>;

    entries: TypedFunctionDescription<{
      encode([_index]: [BigNumberish]): string;
    }>;

    inRegistry: TypedFunctionDescription<{encode([_pool]: [string]): string}>;

    removeSmartPool: TypedFunctionDescription<{
      encode([_index]: [BigNumberish]): string;
    }>;
  };

  events: {};
}

export class ISmartPoolRegistry extends Contract {
  connect(signerOrProvider: Signer | Provider | string): ISmartPoolRegistry;
  attach(addressOrName: string): ISmartPoolRegistry;
  deployed(): Promise<ISmartPoolRegistry>;

  on(event: EventFilter | string, listener: Listener): ISmartPoolRegistry;
  once(event: EventFilter | string, listener: Listener): ISmartPoolRegistry;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ISmartPoolRegistry;
  removeAllListeners(eventName: EventFilter | string): ISmartPoolRegistry;
  removeListener(eventName: any, listener: Listener): ISmartPoolRegistry;

  interface: ISmartPoolRegistryInterface;

  functions: {
    addSmartPool(
      _smartPool: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "addSmartPool(address)"(
      _smartPool: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    entries(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "entries(uint256)"(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    inRegistry(
      _pool: string,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    "inRegistry(address)"(
      _pool: string,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    removeSmartPool(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "removeSmartPool(uint256)"(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  addSmartPool(
    _smartPool: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "addSmartPool(address)"(
    _smartPool: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  entries(
    _index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "entries(uint256)"(
    _index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  inRegistry(_pool: string, overrides?: TransactionOverrides): Promise<boolean>;

  "inRegistry(address)"(
    _pool: string,
    overrides?: TransactionOverrides
  ): Promise<boolean>;

  removeSmartPool(
    _index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "removeSmartPool(uint256)"(
    _index: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {};

  estimate: {
    addSmartPool(
      _smartPool: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "addSmartPool(address)"(
      _smartPool: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    entries(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "entries(uint256)"(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    inRegistry(
      _pool: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "inRegistry(address)"(
      _pool: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    removeSmartPool(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "removeSmartPool(uint256)"(
      _index: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
