/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface LibFeesInterface extends Interface {
  functions: {
    MAX_ANNUAL_FEE: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {
    AnnualFeeChanged: TypedEventDescription<{
      encodeTopics([oldFee, newFee]: [null, null]): string[];
    }>;

    AnnualFeeClaimed: TypedEventDescription<{
      encodeTopics([amount]: [null]): string[];
    }>;

    FeeRecipientChanged: TypedEventDescription<{
      encodeTopics([oldRecipient, newRecipient]: [
        string | null,
        string | null
      ]): string[];
    }>;
  };
}

export class LibFees extends Contract {
  connect(signerOrProvider: Signer | Provider | string): LibFees;
  attach(addressOrName: string): LibFees;
  deployed(): Promise<LibFees>;

  on(event: EventFilter | string, listener: Listener): LibFees;
  once(event: EventFilter | string, listener: Listener): LibFees;
  addListener(eventName: EventFilter | string, listener: Listener): LibFees;
  removeAllListeners(eventName: EventFilter | string): LibFees;
  removeListener(eventName: any, listener: Listener): LibFees;

  interface: LibFeesInterface;

  functions: {
    MAX_ANNUAL_FEE(): Promise<BigNumber>;
  };

  MAX_ANNUAL_FEE(): Promise<BigNumber>;

  filters: {
    AnnualFeeChanged(oldFee: null, newFee: null): EventFilter;

    AnnualFeeClaimed(amount: null): EventFilter;

    FeeRecipientChanged(
      oldRecipient: string | null,
      newRecipient: string | null
    ): EventFilter;
  };

  estimate: {
    MAX_ANNUAL_FEE(): Promise<BigNumber>;
  };
}
