/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface MindfulProxyInterface extends Interface {
  functions: {
    WETH: TypedFunctionDescription<{encode([]: []): string}>;

    addSellStrategy: TypedFunctionDescription<{
      encode([_chakra, _name, _prices, _sellTokens]: [
        string,
        string,
        BigNumberish[],
        string[]
      ]): string;
    }>;

    balancerFactory: TypedFunctionDescription<{encode([]: []): string}>;

    buyStrategies: TypedFunctionDescription<{
      encode([]: [BigNumberish]): string;
    }>;

    buyStrategyChakra: TypedFunctionDescription<{
      encode([]: [BigNumberish]): string;
    }>;

    calcToChakra: TypedFunctionDescription<{
      encode([_chakra, _curreny, _poolAmount, isRelayer]: [
        string,
        string,
        BigNumberish,
        boolean
      ]): string;
    }>;

    chakraManager: TypedFunctionDescription<{encode([]: [string]): string}>;

    chakras: TypedFunctionDescription<{encode([]: [BigNumberish]): string}>;

    disableSellStrategy: TypedFunctionDescription<{
      encode([_chakra, _sellStrategyId]: [string, BigNumberish]): string;
    }>;

    fromChakra: TypedFunctionDescription<{
      encode([_chakra, _quoteToken, _poolAmountOut]: [
        string,
        string,
        BigNumberish
      ]): string;
    }>;

    getChakras: TypedFunctionDescription<{encode([]: []): string}>;

    init: TypedFunctionDescription<{
      encode([_balancerFactory, _implementation]: [string, string]): string;
    }>;

    isChakra: TypedFunctionDescription<{encode([]: [string]): string}>;

    isPaused: TypedFunctionDescription<{encode([]: []): string}>;

    newProxiedSmartPool: TypedFunctionDescription<{
      encode([
        _name,
        _symbol,
        _initialSupply,
        _tokens,
        _amounts,
        _weights,
        _cap
      ]: [
        string,
        string,
        BigNumberish,
        string[],
        BigNumberish[],
        BigNumberish[],
        BigNumberish
      ]): string;
    }>;

    saveEth: TypedFunctionDescription<{encode([]: []): string}>;

    saveToken: TypedFunctionDescription<{encode([_token]: [string]): string}>;

    sellStrategies: TypedFunctionDescription<{
      encode([]: [BigNumberish]): string;
    }>;

    sellStrategyChakra: TypedFunctionDescription<{
      encode([]: [BigNumberish]): string;
    }>;

    setImplementation: TypedFunctionDescription<{
      encode([_implementation]: [string]): string;
    }>;

    smartPoolImplementation: TypedFunctionDescription<{encode([]: []): string}>;

    toChakra: TypedFunctionDescription<{
      encode([_chakra, _baseToken, _poolAmount, _baseAmount, _buyStrategyId]: [
        string,
        string,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ]): string;
    }>;

    togglePause: TypedFunctionDescription<{encode([]: []): string}>;

    transferOwnership: TypedFunctionDescription<{
      encode([_newOwner]: [string]): string;
    }>;
  };

  events: {
    BuyStrategyAdded: TypedEventDescription<{
      encodeTopics([chakra, buyStrategyId]: [
        string | null,
        BigNumberish | null
      ]): string[];
    }>;

    BuyStrategyDisabled: TypedEventDescription<{
      encodeTopics([chakra, buyStrategyId]: [
        string | null,
        BigNumberish | null
      ]): string[];
    }>;

    OwnerChanged: TypedEventDescription<{
      encodeTopics([previousOwner, newOwner]: [
        string | null,
        string | null
      ]): string[];
    }>;

    SellStrategyAdded: TypedEventDescription<{
      encodeTopics([chakra, sellStrategyName, sellStrategyId]: [
        string | null,
        null,
        BigNumberish | null
      ]): string[];
    }>;

    SellStrategyDisabled: TypedEventDescription<{
      encodeTopics([chakra, buyStrategyId]: [
        string | null,
        BigNumberish | null
      ]): string[];
    }>;

    SmartPoolCreated: TypedEventDescription<{
      encodeTopics([poolAddress, chakraManager, name, symbol]: [
        string | null,
        string | null,
        null,
        null
      ]): string[];
    }>;
  };
}

export class MindfulProxy extends Contract {
  connect(signerOrProvider: Signer | Provider | string): MindfulProxy;
  attach(addressOrName: string): MindfulProxy;
  deployed(): Promise<MindfulProxy>;

  on(event: EventFilter | string, listener: Listener): MindfulProxy;
  once(event: EventFilter | string, listener: Listener): MindfulProxy;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): MindfulProxy;
  removeAllListeners(eventName: EventFilter | string): MindfulProxy;
  removeListener(eventName: any, listener: Listener): MindfulProxy;

  interface: MindfulProxyInterface;

  functions: {
    WETH(overrides?: TransactionOverrides): Promise<string>;

    "WETH()"(overrides?: TransactionOverrides): Promise<string>;

    addSellStrategy(
      _chakra: string,
      _name: string,
      _prices: BigNumberish[],
      _sellTokens: string[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "addSellStrategy(address,string,uint256[],address[])"(
      _chakra: string,
      _name: string,
      _prices: BigNumberish[],
      _sellTokens: string[],
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    balancerFactory(overrides?: TransactionOverrides): Promise<string>;

    "balancerFactory()"(overrides?: TransactionOverrides): Promise<string>;

    buyStrategies(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      name: string;
      id: BigNumber;
      interBuyDelay: BigNumber;
      buyAmount: BigNumber;
      lastBuyTimestamp: BigNumber;
      buyToken: string;
      isActive: boolean;
      0: string;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
    }>;

    "buyStrategies(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      name: string;
      id: BigNumber;
      interBuyDelay: BigNumber;
      buyAmount: BigNumber;
      lastBuyTimestamp: BigNumber;
      buyToken: string;
      isActive: boolean;
      0: string;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
    }>;

    buyStrategyChakra(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "buyStrategyChakra(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    calcToChakra(
      _chakra: string,
      _curreny: string,
      _poolAmount: BigNumberish,
      isRelayer: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "calcToChakra(address,address,uint256,bool)"(
      _chakra: string,
      _curreny: string,
      _poolAmount: BigNumberish,
      isRelayer: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    chakraManager(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "chakraManager(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    chakras(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "chakras(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    disableSellStrategy(
      _chakra: string,
      _sellStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "disableSellStrategy(address,uint256)"(
      _chakra: string,
      _sellStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    fromChakra(
      _chakra: string,
      _quoteToken: string,
      _poolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "fromChakra(address,address,uint256)"(
      _chakra: string,
      _quoteToken: string,
      _poolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "fromChakra(address,address,uint256,uint256)"(
      _chakra: string,
      _quoteToken: string,
      _poolAmount: BigNumberish,
      _minQuoteToken: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    getChakras(overrides?: TransactionOverrides): Promise<string[]>;

    "getChakras()"(overrides?: TransactionOverrides): Promise<string[]>;

    init(
      _balancerFactory: string,
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "init(address,address)"(
      _balancerFactory: string,
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    isChakra(arg0: string, overrides?: TransactionOverrides): Promise<boolean>;

    "isChakra(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    isPaused(overrides?: TransactionOverrides): Promise<boolean>;

    "isPaused()"(overrides?: TransactionOverrides): Promise<boolean>;

    newProxiedSmartPool(
      _name: string,
      _symbol: string,
      _initialSupply: BigNumberish,
      _tokens: string[],
      _amounts: BigNumberish[],
      _weights: BigNumberish[],
      _cap: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "newProxiedSmartPool(string,string,uint256,address[],uint256[],uint256[],uint256)"(
      _name: string,
      _symbol: string,
      _initialSupply: BigNumberish,
      _tokens: string[],
      _amounts: BigNumberish[],
      _weights: BigNumberish[],
      _cap: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    saveEth(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    "saveEth()"(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    saveToken(
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "saveToken(address)"(
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    sellStrategies(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      name: string;
      id: BigNumber;
      isActive: boolean;
      0: string;
      1: BigNumber;
      2: boolean;
    }>;

    "sellStrategies(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<{
      name: string;
      id: BigNumber;
      isActive: boolean;
      0: string;
      1: BigNumber;
      2: boolean;
    }>;

    sellStrategyChakra(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "sellStrategyChakra(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    setImplementation(
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setImplementation(address)"(
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    smartPoolImplementation(overrides?: TransactionOverrides): Promise<string>;

    "smartPoolImplementation()"(
      overrides?: TransactionOverrides
    ): Promise<string>;

    toChakra(
      _chakra: string,
      _baseToken: string,
      _poolAmount: BigNumberish,
      _baseAmount: BigNumberish,
      _buyStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "toChakra(address,address,uint256,uint256,uint256)"(
      _chakra: string,
      _baseToken: string,
      _poolAmount: BigNumberish,
      _baseAmount: BigNumberish,
      _buyStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    togglePause(overrides?: TransactionOverrides): Promise<ContractTransaction>;

    "togglePause()"(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    transferOwnership(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;
  };

  WETH(overrides?: TransactionOverrides): Promise<string>;

  "WETH()"(overrides?: TransactionOverrides): Promise<string>;

  addSellStrategy(
    _chakra: string,
    _name: string,
    _prices: BigNumberish[],
    _sellTokens: string[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "addSellStrategy(address,string,uint256[],address[])"(
    _chakra: string,
    _name: string,
    _prices: BigNumberish[],
    _sellTokens: string[],
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  balancerFactory(overrides?: TransactionOverrides): Promise<string>;

  "balancerFactory()"(overrides?: TransactionOverrides): Promise<string>;

  buyStrategies(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    name: string;
    id: BigNumber;
    interBuyDelay: BigNumber;
    buyAmount: BigNumber;
    lastBuyTimestamp: BigNumber;
    buyToken: string;
    isActive: boolean;
    0: string;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: string;
    6: boolean;
  }>;

  "buyStrategies(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    name: string;
    id: BigNumber;
    interBuyDelay: BigNumber;
    buyAmount: BigNumber;
    lastBuyTimestamp: BigNumber;
    buyToken: string;
    isActive: boolean;
    0: string;
    1: BigNumber;
    2: BigNumber;
    3: BigNumber;
    4: BigNumber;
    5: string;
    6: boolean;
  }>;

  buyStrategyChakra(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "buyStrategyChakra(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  calcToChakra(
    _chakra: string,
    _curreny: string,
    _poolAmount: BigNumberish,
    isRelayer: boolean,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "calcToChakra(address,address,uint256,bool)"(
    _chakra: string,
    _curreny: string,
    _poolAmount: BigNumberish,
    isRelayer: boolean,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  chakraManager(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "chakraManager(address)"(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  chakras(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "chakras(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  disableSellStrategy(
    _chakra: string,
    _sellStrategyId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "disableSellStrategy(address,uint256)"(
    _chakra: string,
    _sellStrategyId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  fromChakra(
    _chakra: string,
    _quoteToken: string,
    _poolAmountOut: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "fromChakra(address,address,uint256)"(
    _chakra: string,
    _quoteToken: string,
    _poolAmountOut: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<BigNumber>;

  "fromChakra(address,address,uint256,uint256)"(
    _chakra: string,
    _quoteToken: string,
    _poolAmount: BigNumberish,
    _minQuoteToken: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  getChakras(overrides?: TransactionOverrides): Promise<string[]>;

  "getChakras()"(overrides?: TransactionOverrides): Promise<string[]>;

  init(
    _balancerFactory: string,
    _implementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "init(address,address)"(
    _balancerFactory: string,
    _implementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  isChakra(arg0: string, overrides?: TransactionOverrides): Promise<boolean>;

  "isChakra(address)"(
    arg0: string,
    overrides?: TransactionOverrides
  ): Promise<boolean>;

  isPaused(overrides?: TransactionOverrides): Promise<boolean>;

  "isPaused()"(overrides?: TransactionOverrides): Promise<boolean>;

  newProxiedSmartPool(
    _name: string,
    _symbol: string,
    _initialSupply: BigNumberish,
    _tokens: string[],
    _amounts: BigNumberish[],
    _weights: BigNumberish[],
    _cap: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "newProxiedSmartPool(string,string,uint256,address[],uint256[],uint256[],uint256)"(
    _name: string,
    _symbol: string,
    _initialSupply: BigNumberish,
    _tokens: string[],
    _amounts: BigNumberish[],
    _weights: BigNumberish[],
    _cap: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  saveEth(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  "saveEth()"(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  saveToken(
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "saveToken(address)"(
    _token: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  sellStrategies(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    name: string;
    id: BigNumber;
    isActive: boolean;
    0: string;
    1: BigNumber;
    2: boolean;
  }>;

  "sellStrategies(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<{
    name: string;
    id: BigNumber;
    isActive: boolean;
    0: string;
    1: BigNumber;
    2: boolean;
  }>;

  sellStrategyChakra(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "sellStrategyChakra(uint256)"(
    arg0: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  setImplementation(
    _implementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setImplementation(address)"(
    _implementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  smartPoolImplementation(overrides?: TransactionOverrides): Promise<string>;

  "smartPoolImplementation()"(
    overrides?: TransactionOverrides
  ): Promise<string>;

  toChakra(
    _chakra: string,
    _baseToken: string,
    _poolAmount: BigNumberish,
    _baseAmount: BigNumberish,
    _buyStrategyId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "toChakra(address,address,uint256,uint256,uint256)"(
    _chakra: string,
    _baseToken: string,
    _poolAmount: BigNumberish,
    _baseAmount: BigNumberish,
    _buyStrategyId: BigNumberish,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  togglePause(overrides?: TransactionOverrides): Promise<ContractTransaction>;

  "togglePause()"(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  transferOwnership(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  filters: {
    BuyStrategyAdded(
      chakra: string | null,
      buyStrategyId: BigNumberish | null
    ): EventFilter;

    BuyStrategyDisabled(
      chakra: string | null,
      buyStrategyId: BigNumberish | null
    ): EventFilter;

    OwnerChanged(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    SellStrategyAdded(
      chakra: string | null,
      sellStrategyName: null,
      sellStrategyId: BigNumberish | null
    ): EventFilter;

    SellStrategyDisabled(
      chakra: string | null,
      buyStrategyId: BigNumberish | null
    ): EventFilter;

    SmartPoolCreated(
      poolAddress: string | null,
      chakraManager: string | null,
      name: null,
      symbol: null
    ): EventFilter;
  };

  estimate: {
    WETH(overrides?: TransactionOverrides): Promise<BigNumber>;

    "WETH()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    addSellStrategy(
      _chakra: string,
      _name: string,
      _prices: BigNumberish[],
      _sellTokens: string[],
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "addSellStrategy(address,string,uint256[],address[])"(
      _chakra: string,
      _name: string,
      _prices: BigNumberish[],
      _sellTokens: string[],
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    balancerFactory(overrides?: TransactionOverrides): Promise<BigNumber>;

    "balancerFactory()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    buyStrategies(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "buyStrategies(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    buyStrategyChakra(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "buyStrategyChakra(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    calcToChakra(
      _chakra: string,
      _curreny: string,
      _poolAmount: BigNumberish,
      isRelayer: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "calcToChakra(address,address,uint256,bool)"(
      _chakra: string,
      _curreny: string,
      _poolAmount: BigNumberish,
      isRelayer: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    chakraManager(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "chakraManager(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    chakras(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "chakras(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    disableSellStrategy(
      _chakra: string,
      _sellStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "disableSellStrategy(address,uint256)"(
      _chakra: string,
      _sellStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    fromChakra(
      _chakra: string,
      _quoteToken: string,
      _poolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "fromChakra(address,address,uint256)"(
      _chakra: string,
      _quoteToken: string,
      _poolAmountOut: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "fromChakra(address,address,uint256,uint256)"(
      _chakra: string,
      _quoteToken: string,
      _poolAmount: BigNumberish,
      _minQuoteToken: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    getChakras(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getChakras()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    init(
      _balancerFactory: string,
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "init(address,address)"(
      _balancerFactory: string,
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    isChakra(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "isChakra(address)"(
      arg0: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    isPaused(overrides?: TransactionOverrides): Promise<BigNumber>;

    "isPaused()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    newProxiedSmartPool(
      _name: string,
      _symbol: string,
      _initialSupply: BigNumberish,
      _tokens: string[],
      _amounts: BigNumberish[],
      _weights: BigNumberish[],
      _cap: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "newProxiedSmartPool(string,string,uint256,address[],uint256[],uint256[],uint256)"(
      _name: string,
      _symbol: string,
      _initialSupply: BigNumberish,
      _tokens: string[],
      _amounts: BigNumberish[],
      _weights: BigNumberish[],
      _cap: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    saveEth(overrides?: TransactionOverrides): Promise<BigNumber>;

    "saveEth()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    saveToken(
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "saveToken(address)"(
      _token: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    sellStrategies(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "sellStrategies(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    sellStrategyChakra(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "sellStrategyChakra(uint256)"(
      arg0: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    setImplementation(
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setImplementation(address)"(
      _implementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    smartPoolImplementation(
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "smartPoolImplementation()"(
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    toChakra(
      _chakra: string,
      _baseToken: string,
      _poolAmount: BigNumberish,
      _baseAmount: BigNumberish,
      _buyStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "toChakra(address,address,uint256,uint256,uint256)"(
      _chakra: string,
      _baseToken: string,
      _poolAmount: BigNumberish,
      _baseAmount: BigNumberish,
      _buyStrategyId: BigNumberish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    togglePause(overrides?: TransactionOverrides): Promise<BigNumber>;

    "togglePause()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    transferOwnership(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
