/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface OwnableStorageInterface extends Interface {
  functions: {
    oSlot: TypedFunctionDescription<{encode([]: []): string}>;
  };

  events: {};
}

export class OwnableStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): OwnableStorage;
  attach(addressOrName: string): OwnableStorage;
  deployed(): Promise<OwnableStorage>;

  on(event: EventFilter | string, listener: Listener): OwnableStorage;
  once(event: EventFilter | string, listener: Listener): OwnableStorage;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): OwnableStorage;
  removeAllListeners(eventName: EventFilter | string): OwnableStorage;
  removeListener(eventName: any, listener: Listener): OwnableStorage;

  interface: OwnableStorageInterface;

  functions: {
    oSlot(overrides?: TransactionOverrides): Promise<string>;

    "oSlot()"(overrides?: TransactionOverrides): Promise<string>;
  };

  oSlot(overrides?: TransactionOverrides): Promise<string>;

  "oSlot()"(overrides?: TransactionOverrides): Promise<string>;

  filters: {};

  estimate: {
    oSlot(overrides?: TransactionOverrides): Promise<BigNumber>;

    "oSlot()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
