/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PBasicSmartPoolStorageInterface extends Interface {
  functions: {
    pbsSlot: TypedFunctionDescription<{encode([]: []): string}>;
  };

  events: {};
}

export class PBasicSmartPoolStorage extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PBasicSmartPoolStorage;
  attach(addressOrName: string): PBasicSmartPoolStorage;
  deployed(): Promise<PBasicSmartPoolStorage>;

  on(event: EventFilter | string, listener: Listener): PBasicSmartPoolStorage;
  once(event: EventFilter | string, listener: Listener): PBasicSmartPoolStorage;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PBasicSmartPoolStorage;
  removeAllListeners(eventName: EventFilter | string): PBasicSmartPoolStorage;
  removeListener(eventName: any, listener: Listener): PBasicSmartPoolStorage;

  interface: PBasicSmartPoolStorageInterface;

  functions: {
    pbsSlot(overrides?: TransactionOverrides): Promise<string>;

    "pbsSlot()"(overrides?: TransactionOverrides): Promise<string>;
  };

  pbsSlot(overrides?: TransactionOverrides): Promise<string>;

  "pbsSlot()"(overrides?: TransactionOverrides): Promise<string>;

  filters: {};

  estimate: {
    pbsSlot(overrides?: TransactionOverrides): Promise<BigNumber>;

    "pbsSlot()"(overrides?: TransactionOverrides): Promise<BigNumber>;
  };
}
