/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractFactory, Signer} from "ethers";
import {Provider} from "ethers/providers";
import {UnsignedTransaction} from "ethers/utils/transaction";

import {TransactionOverrides} from ".";
import {PcTokenStorage} from "./PcTokenStorage";

export class PcTokenStorageFactory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: TransactionOverrides): Promise<PcTokenStorage> {
    return super.deploy(overrides) as Promise<PcTokenStorage>;
  }
  getDeployTransaction(overrides?: TransactionOverrides): UnsignedTransaction {
    return super.getDeployTransaction(overrides);
  }
  attach(address: string): PcTokenStorage {
    return super.attach(address) as PcTokenStorage;
  }
  connect(signer: Signer): PcTokenStorageFactory {
    return super.connect(signer) as PcTokenStorageFactory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PcTokenStorage {
    return new Contract(address, _abi, signerOrProvider) as PcTokenStorage;
  }
}

const _abi = [
  {
    inputs: [],
    name: "ptSlot",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32"
      }
    ],
    stateMutability: "view",
    type: "function"
  }
];

const _bytecode =
  "0x60bb610024600b82828239805160001a607314601757fe5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063ec565ffe146038575b600080fd5b603e6050565b60408051918252519081900360200190f35b604080517f5043546f6b656e2e73746f726167652e6c6f636174696f6e0000000000000000815290519081900360180190208156fea26469706673582212204ba1fb89fb7f2e062e702235e66d117868eda299046e58b4cb758cfe0847476a64736f6c63430006040033";
