/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import {Contract, ContractTransaction, EventFilter, Signer} from "ethers";
import {Listener, Provider} from "ethers/providers";
import {Arrayish, BigNumber, BigNumberish, Interface} from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface PProxyPausableInterface extends Interface {
  functions: {
    addressToBytes32: TypedFunctionDescription<{
      encode([_value]: [string]): string;
    }>;

    bytes32ToAddress: TypedFunctionDescription<{
      encode([_value]: [Arrayish]): string;
    }>;

    bytes32ToString: TypedFunctionDescription<{
      encode([_value]: [Arrayish]): string;
    }>;

    getImplementation: TypedFunctionDescription<{encode([]: []): string}>;

    getPaused: TypedFunctionDescription<{encode([]: []): string}>;

    getPauzer: TypedFunctionDescription<{encode([]: []): string}>;

    getProxyOwner: TypedFunctionDescription<{encode([]: []): string}>;

    readAddress: TypedFunctionDescription<{encode([_key]: [Arrayish]): string}>;

    readBool: TypedFunctionDescription<{encode([_key]: [Arrayish]): string}>;

    readString: TypedFunctionDescription<{encode([_key]: [Arrayish]): string}>;

    renouncePauzer: TypedFunctionDescription<{encode([]: []): string}>;

    setImplementation: TypedFunctionDescription<{
      encode([_newImplementation]: [string]): string;
    }>;

    setPaused: TypedFunctionDescription<{encode([_value]: [boolean]): string}>;

    setPauzer: TypedFunctionDescription<{
      encode([_newPauzer]: [string]): string;
    }>;

    setProxyOwner: TypedFunctionDescription<{
      encode([_newOwner]: [string]): string;
    }>;

    storageRead: TypedFunctionDescription<{encode([_key]: [Arrayish]): string}>;

    stringToBytes32: TypedFunctionDescription<{
      encode([_value]: [string]): string;
    }>;
  };

  events: {};
}

export class PProxyPausable extends Contract {
  connect(signerOrProvider: Signer | Provider | string): PProxyPausable;
  attach(addressOrName: string): PProxyPausable;
  deployed(): Promise<PProxyPausable>;

  on(event: EventFilter | string, listener: Listener): PProxyPausable;
  once(event: EventFilter | string, listener: Listener): PProxyPausable;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): PProxyPausable;
  removeAllListeners(eventName: EventFilter | string): PProxyPausable;
  removeListener(eventName: any, listener: Listener): PProxyPausable;

  interface: PProxyPausableInterface;

  functions: {
    addressToBytes32(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    bytes32ToAddress(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "bytes32ToAddress(bytes32)"(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    bytes32ToString(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "bytes32ToString(bytes32)"(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    getImplementation(overrides?: TransactionOverrides): Promise<string>;

    "getImplementation()"(overrides?: TransactionOverrides): Promise<string>;

    getPaused(overrides?: TransactionOverrides): Promise<boolean>;

    "getPaused()"(overrides?: TransactionOverrides): Promise<boolean>;

    getPauzer(overrides?: TransactionOverrides): Promise<string>;

    "getPauzer()"(overrides?: TransactionOverrides): Promise<string>;

    getProxyOwner(overrides?: TransactionOverrides): Promise<string>;

    "getProxyOwner()"(overrides?: TransactionOverrides): Promise<string>;

    readAddress(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "readAddress(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    readBool(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    "readBool(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<boolean>;

    readString(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "readString(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    renouncePauzer(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "renouncePauzer()"(
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setImplementation(
      _newImplementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setImplementation(address)"(
      _newImplementation: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setPaused(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setPaused(bool)"(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setPauzer(
      _newPauzer: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setPauzer(address)"(
      _newPauzer: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    setProxyOwner(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    "setProxyOwner(address)"(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<ContractTransaction>;

    storageRead(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "storageRead(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<string>;

    stringToBytes32(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<string>;

    "stringToBytes32(string)"(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<string>;
  };

  addressToBytes32(
    _value: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "addressToBytes32(address)"(
    _value: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  bytes32ToAddress(
    _value: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "bytes32ToAddress(bytes32)"(
    _value: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  bytes32ToString(
    _value: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "bytes32ToString(bytes32)"(
    _value: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  getImplementation(overrides?: TransactionOverrides): Promise<string>;

  "getImplementation()"(overrides?: TransactionOverrides): Promise<string>;

  getPaused(overrides?: TransactionOverrides): Promise<boolean>;

  "getPaused()"(overrides?: TransactionOverrides): Promise<boolean>;

  getPauzer(overrides?: TransactionOverrides): Promise<string>;

  "getPauzer()"(overrides?: TransactionOverrides): Promise<string>;

  getProxyOwner(overrides?: TransactionOverrides): Promise<string>;

  "getProxyOwner()"(overrides?: TransactionOverrides): Promise<string>;

  readAddress(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "readAddress(bytes32)"(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  readBool(_key: Arrayish, overrides?: TransactionOverrides): Promise<boolean>;

  "readBool(bytes32)"(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<boolean>;

  readString(_key: Arrayish, overrides?: TransactionOverrides): Promise<string>;

  "readString(bytes32)"(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  renouncePauzer(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "renouncePauzer()"(
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setImplementation(
    _newImplementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setImplementation(address)"(
    _newImplementation: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setPaused(
    _value: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setPaused(bool)"(
    _value: boolean,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setPauzer(
    _newPauzer: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setPauzer(address)"(
    _newPauzer: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  setProxyOwner(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  "setProxyOwner(address)"(
    _newOwner: string,
    overrides?: TransactionOverrides
  ): Promise<ContractTransaction>;

  storageRead(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "storageRead(bytes32)"(
    _key: Arrayish,
    overrides?: TransactionOverrides
  ): Promise<string>;

  stringToBytes32(
    _value: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  "stringToBytes32(string)"(
    _value: string,
    overrides?: TransactionOverrides
  ): Promise<string>;

  filters: {};

  estimate: {
    addressToBytes32(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "addressToBytes32(address)"(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    bytes32ToAddress(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "bytes32ToAddress(bytes32)"(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    bytes32ToString(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "bytes32ToString(bytes32)"(
      _value: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    getImplementation(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getImplementation()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    getPaused(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getPaused()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    getPauzer(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getPauzer()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    getProxyOwner(overrides?: TransactionOverrides): Promise<BigNumber>;

    "getProxyOwner()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    readAddress(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "readAddress(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    readBool(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "readBool(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    readString(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "readString(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    renouncePauzer(overrides?: TransactionOverrides): Promise<BigNumber>;

    "renouncePauzer()"(overrides?: TransactionOverrides): Promise<BigNumber>;

    setImplementation(
      _newImplementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setImplementation(address)"(
      _newImplementation: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    setPaused(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setPaused(bool)"(
      _value: boolean,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    setPauzer(
      _newPauzer: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setPauzer(address)"(
      _newPauzer: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    setProxyOwner(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "setProxyOwner(address)"(
      _newOwner: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    storageRead(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "storageRead(bytes32)"(
      _key: Arrayish,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    stringToBytes32(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;

    "stringToBytes32(string)"(
      _value: string,
      overrides?: TransactionOverrides
    ): Promise<BigNumber>;
  };
}
