/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

import { Contract, ContractTransaction, EventFilter, Signer } from "ethers";
import { Listener, Provider } from "ethers/providers";
import { Arrayish, BigNumber, BigNumberish, Interface } from "ethers/utils";
import {
  TransactionOverrides,
  TypedEventDescription,
  TypedFunctionDescription
} from ".";

interface ReentryProtectionStorageInterface extends Interface {
  functions: {
    rpSlot: TypedFunctionDescription<{ encode([]: []): string }>;
  };

  events: {};
}

export class ReentryProtectionStorage extends Contract {
  connect(
    signerOrProvider: Signer | Provider | string
  ): ReentryProtectionStorage;
  attach(addressOrName: string): ReentryProtectionStorage;
  deployed(): Promise<ReentryProtectionStorage>;

  on(event: EventFilter | string, listener: Listener): ReentryProtectionStorage;
  once(
    event: EventFilter | string,
    listener: Listener
  ): ReentryProtectionStorage;
  addListener(
    eventName: EventFilter | string,
    listener: Listener
  ): ReentryProtectionStorage;
  removeAllListeners(eventName: EventFilter | string): ReentryProtectionStorage;
  removeListener(eventName: any, listener: Listener): ReentryProtectionStorage;

  interface: ReentryProtectionStorageInterface;

  functions: {
    rpSlot(): Promise<string>;
  };

  rpSlot(): Promise<string>;

  filters: {};

  estimate: {
    rpSlot(): Promise<BigNumber>;
  };
}
